
package edu.udo.cs.ls14.jf.examples.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnalyzerService", targetNamespace = "http://jaxws.examples.jf.ls14.cs.udo.edu/", wsdlLocation = "http://localhost:8080/emf-ws-example/AnalyzerService?wsdl")
public class AnalyzerService
    extends Service
{

    private final static URL ANALYZERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANALYZERSERVICE_EXCEPTION;
    private final static QName ANALYZERSERVICE_QNAME = new QName("http://jaxws.examples.jf.ls14.cs.udo.edu/", "AnalyzerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/emf-ws-example/AnalyzerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANALYZERSERVICE_WSDL_LOCATION = url;
        ANALYZERSERVICE_EXCEPTION = e;
    }

    public AnalyzerService() {
        super(__getWsdlLocation(), ANALYZERSERVICE_QNAME);
    }

    public AnalyzerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANALYZERSERVICE_QNAME, features);
    }

    public AnalyzerService(URL wsdlLocation) {
        super(wsdlLocation, ANALYZERSERVICE_QNAME);
    }

    public AnalyzerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANALYZERSERVICE_QNAME, features);
    }

    public AnalyzerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalyzerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Analyzer
     */
    @WebEndpoint(name = "AnalyzerPort")
    public Analyzer getAnalyzerPort() {
        return super.getPort(new QName("http://jaxws.examples.jf.ls14.cs.udo.edu/", "AnalyzerPort"), Analyzer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Analyzer
     */
    @WebEndpoint(name = "AnalyzerPort")
    public Analyzer getAnalyzerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.examples.jf.ls14.cs.udo.edu/", "AnalyzerPort"), Analyzer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANALYZERSERVICE_EXCEPTION!= null) {
            throw ANALYZERSERVICE_EXCEPTION;
        }
        return ANALYZERSERVICE_WSDL_LOCATION;
    }

}
