
package edu.udo.cs.ls14.jf.examples.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://jaxws.examples.jf.ls14.cs.udo.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://jaxws.examples.jf.ls14.cs.udo.edu/", className = "edu.udo.cs.ls14.jf.examples.jaxws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jaxws.examples.jf.ls14.cs.udo.edu/", className = "edu.udo.cs.ls14.jf.examples.jaxws.SayHelloResponse")
    @Action(input = "http://jaxws.examples.jf.ls14.cs.udo.edu/Hello/sayHelloRequest", output = "http://jaxws.examples.jf.ls14.cs.udo.edu/Hello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
